#!/bin/bash
port=22
#
if [ $# != 1 ] && [ $# != 2 ]; then
    echo "${WHI}   USE: $0 <IP class>${RES}"
    exit
fi
# Color codes
RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
PURPLE='\033[1;35m'
CYAN='\033[1;36m'
WHITE='\033[1;37m'
RESET='\033[0m'
spinner() {
    local pid=$1
    local delay=0.1
    local spinstr='|/-\'
    while ps -p $pid > /dev/null; do
        local temp=${spinstr#?}
        printf " [%c]  " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done
    printf "    \b\b\b\b"
}

loading_screen() {
    echo "...Cleaning Files..."
    clear
    ( "$@" ) &
    spinner $!
    wait $!  # Wait for the command to finish
    printf "\n"
}


loading_screen sleep 5
clear
echo -e "\033[1;35m  FILES CLEANED\033[0m"
sleep 3
clear
echo -e "${RED}██╗  ██╗ █████╗ ███████╗██╗  ██╗██╗██████╗  █████╗${RESET}                        "
echo -e "${RED}██║  ██║██╔══██╗██╔════╝██║  ██║██║██╔══██╗██╔══██╗${RESET}                       "
echo -e "${YELLOW}███████║███████║███████╗███████║██║██████╔╝███████║${RESET}                       "
echo -e "${YELLOW}██╔══██║██╔══██║╚════██║██╔══██║██║██╔══██╗██╔══██║${RESET}                       "
echo -e "${GREEN}██║  ██║██║  ██║███████║██║  ██║██║██║  ██║██║  ██║${RESET}                       "
echo -e "${BLUE}╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝  ╚═╝╚═╝  ╚═╝${RESET}                       "
echo -e "                                                                          "
echo -e "${PURPLE}███████╗${RED}████████╗${YELLOW} █████╗ ██████╗ ████████╗${BLUE}███████╗${GREEN}██████╗                 ${RESET}"
echo -e "${PURPLE}██╔════╝${RED}╚══██╔══╝${YELLOW}██╔══██╗██╔══██╗╚══██╔══╝${BLUE}██╔════╝${GREEN}██╔══██╗                ${RESET}"
echo -e "${YELLOW}███████╗${RED}   ██║   ${YELLOW}███████║██████╔╝   ██║   ${BLUE}████╗  ${GREEN}██║  ██║                ${RESET}"
echo -e "${YELLOW}╚════██║${RED}   ██║   ${YELLOW}██╔══██║██╔══██╗   ██║   ${BLUE}██╔══╝  ${GREEN}██║  ██║                ${RESET}"
echo -e "${GREEN}███████║${RED}   ██║   ${GREEN}██║  ██║██║  ██║   ██║   ${BLUE}███████╗${YELLOW}██████╔╝                ${RESET}"
echo -e "${GREEN}╚══════╝${RED}   ╚═╝   ${GREEN}╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   ${BLUE}╚══════╝${YELLOW}╚═════╝                 ${RESET}"
./pscan2 $1 $port $2
sleep 5
pkill pscan2
clear
./ssh
echo -e "\033[1;35m ▄▄▄▄    ██▀███   █    ██ ▄▄▄█████▓▓█████   █████▒▒█████   ██▀███   ▄████▄   ██▓ ███▄    █   ▄████ \033[0m"
echo -e "\033[1;35m ▓█████▄ ▓██ ▒ ██▒ ██  ▓██▒▓  ██▒ ▓▒▓█   ▀ ▓██   ▒▒██▒  ██▒▓██ ▒ ██▒▒██▀ ▀█  ▓██▒ ██ ▀█   █  ██▒ ▀█▒ \033[0m"
echo -e "\033[1;35m ▒██▒ ▄██▓██ ░▄█ ▒▓██  ▒██░▒ ▓██░ ▒░▒███   ▒████ ░▒██░  ██▒▓██ ░▄█ ▒▒▓█    ▄ ▒██▒▓██  ▀█ ██▒▒██░▄▄▄░ \033[0m"
echo -e "\033[1;35m ▒██░█▀  ▒██▀▀█▄  ▓▓█  ░██░░ ▓██▓ ░ ▒▓█  ▄ ░▓█▒  ░▒██   ██░▒██▀▀█▄  ▒▓▓▄ ▄██▒░██░▓██▒  ▐▌██▒░▓█  ██▓ \033[0m"
echo -e "\033[1;35m ░▓█  ▀█▓░██▓ ▒██▒▒▒█████▓   ▒██▒ ░ ░▒████▒░▒█░   ░ ████▓▒░░██▓ ▒██▒▒ ▓███▀ ░░██░▒██░   ▓██░░▒▓███▀▒ \033[0m"
echo -e "\033[1;35m ░▒▓███▀▒░ ▒▓ ░▒▓░░▒▓▒ ▒ ▒   ▒ ░░   ░░ ▒░ ░ ▒ ░   ░ ▒░▒░▒░ ░ ▒▓ ░▒▓░░ ░▒ ▒  ░░▓  ░ ▒░   ▒ ▒  ░▒   ▒  \033[0m"
echo -e "\033[1;35m ░▒   ░   ░▒ ░ ▒░░░▒░ ░ ░     ░     ░ ░  ░ ░       ░ ▒ ▒░   ░▒ ░ ▒░  ░  ▒    ▒ ░░ ░░   ░ ▒░  ░   ░  \033[0m"
echo -e "\033[1;35m  ░    ░   ░░   ░  ░░░ ░ ░   ░         ░    ░ ░   ░ ░ ░ ▒    ░░   ░ ░         ▒ ░   ░   ░ ░ ░ ░   ░  \033[0m"
echo -e "\033[1;35m  ░         ░        ░                 ░  ░           ░ ░     ░     ░ ░       ░           ░       ░  \033[0m"
echo -e "\033[1;35m       ░                                                            ░                               \033[0m"
sleep 3
